# Generated by Django 5.0.3 on 2024-04-23 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsCollector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_counted', models.FloatField(default=0)),
                ('value_goal', models.FloatField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_collected', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='collectors', to='campaign.campaign')),
            ],
        ),
    ]
