# Generated by Django 5.0.3 on 2024-04-19 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collector', '0001_initial'),
        ('end_user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='end_user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectors', to='end_user_profile.enduserprofile'),
        ),
        migrations.AddField(
            model_name='collector',
            name='collector_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='collectors', to='collector.collectortype'),
        ),
        migrations.AddField(
            model_name='logscollector',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs_collectors', to='collector.collector'),
        ),
    ]
