# Generated by Django 5.0.3 on 2024-04-18 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_initial'),
        ('end_user_profile', '0002_enduserprofile_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collector',
            name='end_user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectors', to='end_user_profile.enduserprofile'),
        ),
    ]
