name: besmart
dependencies:
  - python=3.12.2
  - psycopg2=2.9.9
  - pip=23.3.1
  - pip:
    - django==5.0.3
    - djangorestframework==3.15.0
    - djangorestframework_simplejwt==5.3.1
    - pillow==10.2.0
    - drf-yasg==1.21.7
    - flake8==7.0.0
    - gunicorn==21.2.0
    - django_cors_headers==4.3.1
    - qrcode==7.4.2
    - segno==1.6.1
    - wallet-py3k==0.0.4