# Generated by Django 5.0.3 on 2024-04-16 16:19

import campaign.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_user_profile', '0002_remove_customeruserprofile_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value_goal', models.FloatField()),
                ('beginning_date', models.DateField(default=campaign.models.get_tomorrow)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to=campaign.models.campaign_directory_path, verbose_name='image')),
                ('logo', models.ImageField(blank=True, upload_to=campaign.models.campaign_directory_path, verbose_name='logo')),
                ('customer_user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='customer_user_profile.customeruserprofile')),
                ('style', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='campaign.campaignstyle')),
            ],
        ),
    ]
