# Generated by Django 5.0.3 on 2024-04-19 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
        ('customer_user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='customer_user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='customer_user_profile.customeruserprofile'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='campaign.campaignstyle'),
        ),
    ]
