# Generated by Django 5.0.3 on 2024-04-23 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='collector_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaigns', to='campaign.collectortype'),
        ),
    ]
