# Generated by Django 5.0.3 on 2024-04-17 14:07

import end_user_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduserprofile',
            name='qr_code',
            field=models.ImageField(default=1, upload_to=end_user_profile.models.end_user_qr_directory_path),
            preserve_default=False,
        ),
    ]
