# Generated by Django 5.0.3 on 2024-04-21 11:09

import end_user_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduserprofile',
            name='serial_nr',
            field=models.CharField(default=end_user_profile.models.code_generator, max_length=15, unique=True),
        ),
    ]
