# Generated by Django 5.0.3 on 2024-04-16 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_profile', '0002_remove_enduserprofile_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enduserprofile',
            name='website',
        ),
    ]
