# Generated by Django 5.0.3 on 2024-04-16 08:58

import end_user_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_profile', '0003_remove_enduserprofile_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduserprofile',
            name='secret_key',
            field=models.CharField(default=end_user_profile.models.code_generator, max_length=15, unique=True),
        ),
    ]
