# Generated by Django 5.0.3 on 2024-04-17 09:35

import django.db.models.deletion
import voucher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
        ('end_user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=voucher.models.voucher_directory_path)),
                ('expiration_date', models.DateField()),
                ('is_used', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='campaign.campaign')),
                ('end_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='end_user_profile.enduserprofile')),
            ],
        ),
    ]
