# Generated by Django 5.0.3 on 2024-04-17 14:07

import voucher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_alter_voucher_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='qr_code',
            field=models.ImageField(default=1, upload_to=voucher.models.voucher_qr_directory_path),
            preserve_default=False,
        ),
    ]
