# Generated by Django 5.0.3 on 2024-04-18 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_user_profile', '0002_enduserprofile_qr_code'),
        ('voucher', '0003_voucher_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='end_user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='end_user_profile.enduserprofile'),
        ),
    ]
