# Generated by Django 5.0.3 on 2024-04-17 09:35

import customer_user_profile.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer_user_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('code', models.CharField(default=customer_user_profile.models.code_generator, max_length=5, unique=True)),
                ('business_name', models.CharField(max_length=100, verbose_name='business name')),
                ('country', models.CharField(max_length=80, verbose_name='country')),
                ('city', models.CharField(max_length=60, verbose_name='city')),
                ('street', models.CharField(max_length=100, verbose_name='street')),
                ('zip', models.CharField(max_length=10, verbose_name='zip')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('logo', models.ImageField(upload_to=customer_user_profile.models.logo_directory_path, verbose_name='logo')),
            ],
        ),
    ]
