# Generated by Django 5.0.3 on 2024-04-17 14:07

import customer_user_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruserprofile',
            name='qr_code',
            field=models.ImageField(default=1, upload_to=customer_user_profile.models.customer_user_qr_directory_path),
            preserve_default=False,
        ),
    ]
