# Generated by Django 5.0.3 on 2024-04-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruserprofile',
            name='date_joined',
        ),
    ]
